package com.mobatia.nasmanila.common.constants

class JSONConstants {
    companion object {
        var JTAG_RESPONSECODE = "responsecode"
        var JTAG_STATUSCODE = "statuscode"
        var JTAG_RESPONSE = "response"
        var JTAG_RESPONSE_DATA_ARRAY = "data"
        var JTAG_RESPONSE_IMAGES_ARRAY = "images"
        var JTAG_STATUS = "Status"
        var JTAG_SUCCESS = "Success"
        var JTAG_ID = "id"
        var JTAG_URL = "url"
        var JTAG_TYPE = "type"
        var JTAG_CONTACT_EMAIL = "contact_email"
        var JTAG_CREATED_ON = "created_on"
        var JTAG_DESCRIPTION = "description"
        var JTAG_IMAGE = "image"
        var JTAG_IMAGE_URL = "image_url"
        var JTAG_VIDEO = "video"
        var JTAG_VIDEO_TYPE = "video_type"
        var JTAG_THUMBNAIL_IMAGE = "thumbnail_image"
        var JTAG_DATE = "date"
        var JTAG_PDF = "pdf"
        var JTAG_BANNER_IMAGE = "banner_image"
        var JTAG_FACEBOOK_URL = "facebookurl"
        var JTAG_STUDENT_ID = "student_id"
        var JTAG_STAFF_ID = "staff_id"
        var JTAG_USERS_ID = "users_id"
        var JTAG_PAGE_FROM = "offset"
        var JTAG_SCROLL_TO = "scroll_to"
        var JTAG_USERS_ID_VALUE = "17"
        var JTAG_TAB_CLASS = "class"
        var JTAG_TAB_DATE = "date"
        var JTAG_TAB_SECTION = "section"
        var JTAG_PUSH_MESSAGE = "message"
        var JTAG_PUSH_URL = "url"
        var JTAG_PUSH_TYPE = "type"
        var JTAG_DEVICE_ID = "deviceId"
        var JTAG_DEVICE_iD = "deviceid"
        var JTAG_DEVICE_TYPE = "deviceType"
        var JTAG_DEVICE_tYPE = "devicetype"
        var JTAG_ACCESSTOKEN = "access_token" //access token


        var JTAG_TAB_TYPE = "tab_type"
        var JTAG_NOTIFICATION_ID = "push_id"

        var JTAG_TAB_NAME = "name"
        var JTAG_TAB_PHOTO = "photo"
        var JTAG_TAB_STAFF_PHOTO = "staff_photo"
        var JTAG_TAB_SUBMENU_ARRAY = "submenu"
        var JTAG_TAB_FILE = "file"
        var JTAG_TITLE = "title"
        var JTAG_TAB_FILE_NAME = "filename"
        var JTAG_USER_ID = "userid"

        var JTAG_EVENT_STARTDATE = "start_date"
        var JTAG_EVENT_ENDDATE = "end_date"
        var JTAG_EVENT_PLACE = "place"
        var JTAG_EVENT_LATITUDE = "latitude"
        var JTAG_EVENT_LONGITUDE = "longitude"
        var JTAG_EVENT_PHONE = "phone"
        var JTAG_EMAIL = "email"
        var JTAG_EVENT_PARTICIPANTS = "participants"
        var JTAG_EVENT_PARTICIPANTS_DETAILS = "participants_details"
        var JTAG_EVENT_BUSROUTES = "bus_routes"
        var JTAG_EVENT_MESSAGE = "message"
        var JTAG_EVENT_LINK = "link"
        var JTAG_EVENT_VENUE = "venue"
        var JTAG_EVENT_BUS_ROUTE = "route_name"
        var JTAG_EVENT_BUS_TIME = "time"
        var JTAG_EVENT_BUS_NO = "bus_no"
        var JTAG_EVENT_BUSNAME = "bus_name"
        var JTAG_EVENT_BUSCONTACT_PESRON = "contact_person"
        var JTAG_EVENT_BUSCONTACT_NO = "contact_no"
        var JTAG_EVENT_GOINGSTATUS = "going_status"


        var JTAG_RESPONSE_ARRAY = "responseArray"
        var JTAG_WEB_LINK = "website_link"
        var JTAG_CONTACTS = "contacts"


        var JTAG_ITEMS = "items"
        var JTAG_ROLE = "role"
        var JTAG_ISPARTICIPANT = "is_participant"


        var JTAG_REQUESTS = "requests"
        var JTAG_REASON = "reason"
        var JTAG_TODATE = "to_date"
        var JTAG_FROMDATE = "from_date"
        var JTAG_STATUs = "status"
    }
}